env:
  browser: true
  es2021: true
  amd: true
  node: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:jest/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "jest"
overrides:
  - files: "*.test.ts"
    rules:
      "@typescript-eslint/no-empty-function": 0
rules: {}
