stages:
  - test
  - release  
 
test_infra:
  image: node:12
  stage: test 
  script:
  - make install
  - make test  

release:
  image: node:12
  stage: release  
  only:
    - master  
  dependencies:
    - test_infra
  script:
    - echo "@greximus-beige:registry=https://gitlab.com/api/v4/packages/npm/"  >> .npmrc
    - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc  
    - npm install
    - npm run build  
    - npm publish 


    

